import { PipePlant, StaticPlant, GreenTurtle, SpikedTurtle, TurtleShell, Gumpa, Mario } from '../figures';
import { Coin, CoinBox, MultipleCoinBox, StarBox, MushroomBox } from '../items';
import {
  RightPipeGrass,
  LeftPipeGrass,
  RightPipeSoil,
  LeftPipeSoil,
  LeftPlantedSoil,
  MiddlePlantedSoil,
  RightPlantedSoil,
  TopRightGrassSoil,
  TopLeftGrassSoil,
  RightBush,
  RightMiddleBush,
  MiddleBush,
  LeftMiddleBush,
  LeftBush,
  Soil,
  RightSoil,
  LeftSoil,
  TopGrass,
  TopRightGrass,
  TopLeftGrass,
  RightGrass,
  LeftGrass,
  TopRightRoundedGrass,
  TopLeftRoundedGrass,
  Stone,
  BrownBlock,
  RightTopPipe,
  LeftTopPipe,
  RightPipe,
  LeftPipe,
  TopRightCornerGrass,
  TopLeftCornerGrass,
} from '../matter';

export const ABV = {
  Pp: PipePlant,
  Sp: StaticPlant,
  Gt: GreenTurtle,
  SpT: SpikedTurtle,
  TS: TurtleShell,
  Bm: Gumpa,
  M: Mario,
  Prg: RightPipeGrass,
  Plg: LeftPipeGrass,
  Prs: RightPipeSoil,
  Pls: LeftPipeSoil,
  Lps: LeftPlantedSoil,
  Mps: MiddlePlantedSoil,
  Rps: RightPlantedSoil,
  Gtrs: TopRightGrassSoil,
  Gtls: TopLeftGrassSoil,
  Br: RightBush,
  Bmr: RightMiddleBush,
  Bc: MiddleBush,
  Bmk: LeftMiddleBush,
  Bl: LeftBush,
  S: Soil,
  Sr: RightSoil,
  Sl: LeftSoil,
  G: TopGrass,
  Gtr: TopRightGrass,
  Gtl: TopLeftGrass,
  Gr: RightGrass,
  Gl: LeftGrass,
  Gtrr: TopRightRoundedGrass,
  Gtlr: TopLeftRoundedGrass,
  St: Stone,
  Bb: BrownBlock,
  Ptr: RightTopPipe,
  Ptl: LeftTopPipe,
  Pr: RightPipe,
  Pl: LeftPipe,
  Gtrc: TopRightCornerGrass,
  Gtlc: TopLeftCornerGrass,
  C: Coin,
  Cb: CoinBox,
  MCb: MultipleCoinBox,
  Sb: StarBox,
  Mb: MushroomBox,
};
